backend:
  name: github
  repo: vuongvu1/today-i-learned

media_folder: content/assets
public_folder: ../assets

collections:
  - name: post
    label: Post
    folder: content/post
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description, required: false }
      - { name: body, label: Body, widget: markdown }
